### ISSUE TITLE
網站架構定義(sitemap)＆麵包屑提出來

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/CTF#1]
麵包屑部分...或許可以試試Laravel Breadcrumbs

**Comment by vongola12324** [comment]
於 657cd60ad3b7b717ceaacc82396d82b99e860e15  
已安裝[Laravel Breadcrumbs](https://github.com/davejamesmiller/laravel-breadcrumbs)  
定義檔：`app/Http/breadcrumbs.php`  
view：`resources/views/breadcrumbs.blade.php`  

---

這套件要求所有路由皆必須命名（本該養成的良好習慣）且定義對應麵包屑（可以關閉這限制，但避免漏掉某些頁面的麵包屑，還是讓它限制吧）  
如果看到以下錯誤訊息  

```
Breadcrumb not found with name "xxxxx"
```

表示定義檔中無該路由的麵包屑  
在該檔案加上對應區段即可  
（格式可以參考該檔其他段落）

**Comment by vongola12324** [comment]
Move From Gitlab Issue [#7](https://gitlab.com/HackerSir/CTF/issues/7)
Create by @jyhsu2000

**Comment by jyhsu2000** [comment]
Finish
